package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.python
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Ansible'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Ansible")) {
    expectSteps {
        python {
            environment = venv {
            }
            command = file {
                filename = "setup.py"
                scriptArguments = "install --user --install-scripts=."
            }
        }
    }
    steps {
        insert(1) {
            python {
                environment = venv {
                }
                command = flake8 {
                    scriptArguments = "--config=setup.cfg"
                }
            }
        }
    }
}
